/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.game_mp;

import java.io.*;
import javax.swing.*;
import com.google.gson.Gson;
import java.net.InetAddress;
import java.net.Socket;
import java.net.ServerSocket;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.*;
/**
 *
 * @author vovab
 */
public class ClientFrame extends javax.swing.JFrame implements IObserver{
    Model m = Build_Model.build();
    Socket clientSocket;
    ClientInfo playerInfo;
    Gson gson = new Gson();
    String name;
    SocketMessage sm;
    ArrayList<javax.swing.JLabel> simple_labels = new ArrayList();
    ArrayList<javax.swing.JLabel> players = new ArrayList();
    ArrayList<PlayerEntity> leaders = new ArrayList();
    ArrayList<javax.swing.JLabel> shoots = new ArrayList();
    ArrayList<javax.swing.JLabel> points = new ArrayList();
    ArrayList<javax.swing.JLabel> wins = new ArrayList();
    
    javax.swing.JLabel pointer;
    //static int players = 0;
    /**
     * Creates new form ClientForm
     */
    public ClientFrame(String playerName) {
        initComponents();
        //m.addTarget(new MyPoint(275, 159, 20), new MyPoint(355, 159, 10));
        m.addObserver(this);
        playerInfo = new ClientInfo(playerName);
        
        //System.out.println(p2.getX()); //setLocation //601,6; 601, 23; 601, 40;  17,22
        //System.out.println(p2.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vModel1 = new com.mycompany.game_mp.VModel();
        Start = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        Shoot = new javax.swing.JButton();
        players2 = new com.mycompany.game_mp.Players();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout vModel1Layout = new javax.swing.GroupLayout(vModel1);
        vModel1.setLayout(vModel1Layout);
        vModel1Layout.setHorizontalGroup(
            vModel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        vModel1Layout.setVerticalGroup(
            vModel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        Start.setText("Ready");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        Stop.setText("Stop");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        Shoot.setText("Shoot");
        Shoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout players2Layout = new javax.swing.GroupLayout(players2);
        players2.setLayout(players2Layout);
        players2Layout.setHorizontalGroup(
            players2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        players2Layout.setVerticalGroup(
            players2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Leaders");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(players2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vModel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Start, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Shoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vModel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Shoot))
            .addComponent(players2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void dataInit(SocketMessage sm, String name) {
        this.sm = sm;
        this.name = name;
    }
    
    private void sendRequest(ClientReq msg)
    {
        try {
            sm.writeData(gson.toJson(msg));
        } catch (IOException ignored) { }
    }
    
//    public void initialize() {
//        m.addObserver(this);
//    }
    
    @Override
    public void update() {
        checkWinner();
        updatePlayers(m.getClientArrayList());
        updatePlayersInfo(m.getClientArrayList());
        //leaders = m.getLeadersArrayList();
        updateTable(m.getLeadersArrayList());
    }
    
    private void checkWinner() {
        if (m.getWinner() != null) {
            JOptionPane.showMessageDialog(this, "Winner is " + m.getWinner());
        }
    }
    
    private synchronized void updateTable(ArrayList<PlayerEntity> a) {
        if (a == null || a.size() == 0) return;
        leaders = a;
    }
    
    private synchronized void updatePlayers(ArrayList<ClientInfo> a) {
        if (a == null || a.size() == 0 || players.size() == a.size()) return;
        for (int i = 0; i < a.size(); i++) {
            if (i>=players.size()) {
                javax.swing.JLabel sl = new javax.swing.JLabel("Игрок: ");
                add(sl);
                sl.setLocation(601, 6 + 75*i);  //56
                sl.setSize(40, 16);
                simple_labels.add(sl);
                
                javax.swing.JLabel sl2 = new javax.swing.JLabel("Счет: ");
                add(sl2);
                sl2.setLocation(601, 23 + 75*i);
                sl2.setSize(40, 16);
                simple_labels.add(sl2);
                
                javax.swing.JLabel sl3 = new javax.swing.JLabel("Выстрелов: ");
                add(sl3);
                sl3.setLocation(601, 40 + 75*i);
                sl3.setSize(80, 16);
                simple_labels.add(sl3);
                
                javax.swing.JLabel sl4 = new javax.swing.JLabel("Побед: ");
                add(sl4);
                sl4.setLocation(601, 57 + 75*i);
                sl4.setSize(80, 16);
                simple_labels.add(sl4);
                
                javax.swing.JLabel l_name = new javax.swing.JLabel(a.get(i).getPlayerName());
                add(l_name);
                l_name.setLocation(641, 6 + 75*i);
                l_name.setSize(100, 16);
                //l.setText(a.get(i).getPlayerName());
                players.add(l_name);
                
                javax.swing.JLabel l_points = new javax.swing.JLabel(String.valueOf(a.get(i).getPoints()));
                add(l_points);
                l_points.setLocation(641, 23 + 75*i);
                l_points.setSize(40, 16);
                //l.setText(a.get(i).getPlayerName());
                points.add(l_points);
                
                javax.swing.JLabel l_shoots = new javax.swing.JLabel(String.valueOf(a.get(i).getArrowsShoot()));
                add(l_shoots);
                l_shoots.setLocation(671, 40 + 75*i);
                l_shoots.setSize(40, 16);
                //l.setText(a.get(i).getPlayerName());
                shoots.add(l_shoots);
                
                javax.swing.JLabel l_wins = new javax.swing.JLabel(String.valueOf(a.get(i).getWins()));
                add(l_wins);
                l_wins.setLocation(671, 57 + 75*i);
                l_wins.setSize(40, 16);
                //l.setText(a.get(i).getPlayerName());
                wins.add(l_wins);
            }
        }
        
        for (int i = 0; i < a.size(); i++) {
            int step = 300 / (a.size() + 1);
            if (a.get(i).getPlayerName().equals(playerInfo.getPlayerName())) {
                if (pointer != null) players2.remove(pointer);
                javax.swing.JLabel you = new javax.swing.JLabel("Вы");
                players2.add(you);
                you.setLocation(10, (i+1)*step-8);
                you.setSize(30,16);
                pointer = you;
            }
        }
    }
    
    private synchronized void updatePlayersInfo(ArrayList<ClientInfo> a) {
        if (a == null || a.size() == 0) return;
        for (int i = 0; i < a.size(); i++) {
            points.get(i).setText(String.valueOf(a.get(i).getPoints()));
            shoots.get(i).setText(String.valueOf(a.get(i).getArrowsShoot()));
            wins.get(i).setText(String.valueOf(a.get(i).getWins()));
        }
    }
    
    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        sendRequest(new ClientReq(ClientActions.READY));
    }//GEN-LAST:event_StartActionPerformed

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        sendRequest(new ClientReq(ClientActions.STOP));
    }//GEN-LAST:event_StopActionPerformed

    private void ShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShootActionPerformed
        sendRequest(new ClientReq(ClientActions.SHOOT));
        System.out.println(m.big.getY());
    }//GEN-LAST:event_ShootActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //sendRequest(new ClientReq(ClientActions.SCORE_TABLE));
        //update();
        
        String[] columnNames = {"Имя", "Число побед"};
        ArrayList<PlayerEntity> data = m.updateLeaders();
        System.out.println(leaders.size());
        Collections.sort(data, new ComparatorEntity());
        int size;
        if (data.size() < 3) size = data.size();
        else size = 3;
        String[][] rowData = new String[size][2];
        for (int i = 0; i < size; i++) {
            rowData[i][0] = data.get(i).getName();
            rowData[i][1] = String.valueOf(data.get(i).getWins());
        }
        javax.swing.JTable table = new javax.swing.JTable(rowData, columnNames);
        //JOptionPane.showMessageDialog(this, table);
        JOptionPane.showMessageDialog(this, table, "Лидеры", 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClientFrame("ttt").setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Shoot;
    private javax.swing.JButton Start;
    private javax.swing.JButton Stop;
    private javax.swing.JButton jButton1;
    private com.mycompany.game_mp.Players players2;
    private com.mycompany.game_mp.VModel vModel1;
    // End of variables declaration//GEN-END:variables
}
