/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.game_mp;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.util.ArrayList;

/**
 *
 * @author vovab
 */
public class Players extends javax.swing.JPanel implements IObserver{
    Model m = Build_Model.build();
    
    private ArrayList<Polygon> playersArrayList = new ArrayList<>();
    private ArrayList<Color> colors = new ArrayList<>();
    /**
     * Creates new form Players
     */
    public Players() {
        initComponents();
        m.addObserver(this);
        colors.add(Color.orange);
        colors.add(Color.blue);
        colors.add(Color.green);
        colors.add(Color.pink);
    }
    
    private synchronized void playersCountUpdate() {
        playersArrayList.clear();
        int clientsCount = m.getClientArrayList().size();
        for (int i = 1; i <= clientsCount; i++) {
            int step = 300 / (clientsCount + 1);
            Polygon p = new Polygon(new int[] {30, 30, 70}, new int[] {step*i - 20, step*i + 20, step*i}, 3);
            playersArrayList.add(p);  
        }
    }
    
    @Override
    public void update (){
        playersCountUpdate();
        this.repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
      
//        Graphics2D g2d = (Graphics2D) g;
//        g2d.setColor(Color.black);
//        g2d.setStroke(new BasicStroke(1));
//        g2d.drawPolygon(new int[] {30, 30, 70}, new int[] {10, 50, 30}, 3);
//        g2d.setStroke(new BasicStroke(3));
//        g2d.drawLine(100, 0, 100, 318);

          Graphics2D g2d = (Graphics2D) g;
          g2d.setStroke(new BasicStroke(2));
          for (int i = 0; i < playersArrayList.size(); i++) {
              g2d.setColor(Color.black);
              g2d.drawPolygon(playersArrayList.get(i));
              g2d.setColor(colors.get(i));
              g2d.fillPolygon(playersArrayList.get(i));
          }
          g2d.setColor(Color.black);
          g2d.setStroke(new BasicStroke(3));
          g2d.drawLine(100, 0, 100, 318);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
