/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.game_mp;

import java.util.*;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.*;
import java.io.*;
import java.net.InetAddress;
import java.net.Socket;

/**
 *
 * @author vovab
 */
public class VModel extends javax.swing.JPanel implements IObserver {
    int x1 = 0, x2 = 30;
    int bx = 275, by = 159, br = 20;
    int sx = 355, sy = 159, sr = 10;
    int lbx = 275; int lsx = 355; 
    
    Model m = Build_Model.build();
    
    PointAction action;
    public void setAction(PointAction action) {
        this.action = action;
    }
    /**
     * Creates new form Vmodel
     */
    
    public VModel() {
        initComponents();
        m.addObserver(this);
    }
    
    @Override
    public void update() {
        this.repaint();
        //System.out.println(m.big.getY());
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        Graphics2D big = (Graphics2D) g;
        big.setColor(Color.black);
        big.setStroke(new BasicStroke(1)); //fix paint model//fix paint model//fix paint model//fix paint model
        big.drawLine(bx, 0, bx, 318);
        big.setStroke(new BasicStroke(3));
        big.drawOval(m.big.getX()-br,m.big.getY()-br, 2*br, 2*br);
        big.setColor(Color.red);
        big.fillOval(m.big.getX()-br, m.big.getY()-br, 2*br, 2*br);
        
        Graphics2D small = (Graphics2D) g;
        small.setColor(Color.black);
        small.setStroke(new BasicStroke(1));
        small.drawLine(sx, 0, sx, 318);
        small.setStroke(new BasicStroke(3));
        small.drawOval(m.small.getX()-sr, m.small.getY()-sr, 2*sr, 2*sr);
        small.setColor(Color.red);
        small.fillOval(m.small.getX()-sr, m.small.getY()-sr, 2*sr, 2*sr);
//        Graphics2D g2d = (Graphics2D) g;
//        g2d.setColor(Color.black);
//        g2d.setStroke(new BasicStroke(1));
//        g2d.drawLine(lbx, 0, lbx, 318);
//        g2d.drawLine(lsx, 0, lsx, 318);
        
//        for (MyPoint point: m.getTargetArrayList()) {
//            int x = point.getX();
//            int y = point.getY();
//            int r = point.getR();
//            
//            g2d.setStroke(new BasicStroke(3));
//            g2d.drawOval(x-r, x-r, 2*r, 2*r);
//            g2d.setColor(Color.red);
//            g2d.fillOval(x-r, y-r, 2*r, 2*r);
//        }
        
        Graphics2D arw = (Graphics2D) g;
        for (MyPoint point: m.getArrowArrayList()) {
            int x = point.getX();
            int y = point.getY();
            int r = point.getR();
            
        //    Graphics2D arw = (Graphics2D) g;
            arw.setColor(Color.black);
            arw.setStroke(new BasicStroke(2));
            arw.drawLine(x, y, x+r, y);
            
//            javax.swing.JLabel l = new javax.swing.JLabel("Вы");
//            add(l);
//            l.setLocation(x, y-20);
//            l.setSize(30,16);
        }
//        for (javax.swing.JLabel l:m.getLabelArrayList()) {
//            //int x = l.getLocation().x;
//            //int y = l.getLocation().y;
//            add(l);
//        }
    }
    
//    public void moveBig(int mov) { //mov - napravlenie
//      //this.big+=5*mov;
//      m.big.setY(m.big.getY()+5*mov);
//      m.update();
//      this.update();
//    }
//    
//    public void moveSmall(int mov) { //mov - napravlenie
//      //this.big+=5*mov;
//      m.small.setY(m.small.getY()+5*mov);
//      m.update();
//      this.update();
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
